id: 33394426-a074-4ec8-9207-231b46c1b5bb
name: Identity Service - Dev
values:
  - key: baseUrl
    value: 'http://localhost:3001'
    enabled: true
    type: default
_postman_variable_scope: environment
color: 120
